package com.example.projektmobpravi.ui.theme

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    val languageCode: String,
    // Common
    val cancel: String,
    val delete: String,
    val close: String,
    val select: String,
    val or_: String,
    // Bottom nav
    val navHome: String,
    val navStats: String,
    val navAdd: String,
    val navBudget: String,
    // Home screen
    val greeting: String,
    val spendingThisMonth: String,
    val activeTracking: String,
    val topCategories: String,
    val recentTransactions: String,
    val searchResults: String,
    val itemsSuffix: String,
    val searchHint: String,
    val noTransactions: String,
    val noTransactionsHint: String,
    val offlineBanner: String,
    val shakeTipShake: String,
    val shakeTipDouble: String,
    val deleteTransactionTitle: String,
    val deleteTransactionMessage: String,
    // Stats screen
    val statsTitle: String,
    val statsSubtitle: String,
    val filterByDay: String,
    val expenseDistribution: String,
    val spendingByCategory: String,
    val last7Days: String,
    val totalLabel: String,
    val dailyLabel: String,
    val lastMonthLabel: String,
    val noDataForPeriod: String,
    val csvExportSuccess: String,
    val csvExportError: String,
    val periodThisWeek: String,
    val periodThisMonth: String,
    val periodLastMonth: String,
    val periodThisQuarter: String,
    val periodThisYear: String,
    val allCategories: String,
    val filterCategoriesTitle: String,
    val categoriesAvailableSuffix: String,
    val showingPrefix: String,
    val removeFilter: String,
    // Category display names
    val catFood: String,
    val catShopping: String,
    val catTransport: String,
    val catEntertainment: String,
    val catHousing: String,
    val catHealth: String,
    val catClothing: String,
    val catBeauty: String,
    val catOther: String,
    // Login
    val loginSubtitle: String,
    val loginWelcome: String,
    val loginWelcomeSub: String,
    val passwordLabel: String,
    val rememberMe: String,
    val loginButton: String,
    val noAccount: String,
    // Register
    val registerHeadline: String,
    val registerSubtitle: String,
    val registerCardTitle: String,
    val registerCardSubtitle: String,
    val usernameLabel: String,
    val confirmPasswordLabel: String,
    val registerButton: String,
    val hasAccount: String,
    // AddTransaction
    val addNewTransaction: String,
    val editTransaction: String,
    val amountLabel: String,
    val scanButton: String,
    val voiceButton: String,
    val voiceListening: String,
    val voiceLangLabel: String,
    val voiceHelpTitle: String,
    val voiceHelpDesc: String,
    val voiceExamplesCroatian: String,
    val voiceExamplesEnglish: String,
    val voiceDecimalTip: String,
    val voiceHelpOk: String,
    val voiceRecognizedLabel: String,
    val voiceNotRecognizedPrefix: String,
    val voiceNoSpeech: String,
    val voiceNoPerm: String,
    val categoryLabel: String,
    val addNewCategoryLabel: String,
    val noteLabel: String,
    val notePlaceholder: String,
    val amountFromScan: String,
    val saveChanges: String,
    val addTransactionButton: String,
    val deleteCategoryTitle: String,
    val deleteCategoryMessage: String,
    // Budget
    val budgetSubtitle: String,
    val budgetSummaryTitle: String,
    val budgetCategorySection: String,
    val budgetOverLimitSingular: String,
    val budgetOverLimitPlural: String,
    val budgetSetLimitHint: String,
    val budgetWithinBudget: String,
    val budgetNoLimitFormat: String,
    val budgetExceededByFormat: String,
    val budgetTapToSet: String,
    val budgetDialogSetLimit: String,
    val budgetSave: String,
    val budgetRemoveLimit: String,
    val loadMore: String,
) {
    fun categoryDisplayName(category: String): String = when (category) {
        "Hrana"      -> catFood
        "Trgovina"   -> catShopping
        "Prijevoz"   -> catTransport
        "Zabava"     -> catEntertainment
        "Kuća"       -> catHousing
        "Zdravlje"   -> catHealth
        "Odijevanje" -> catClothing
        "Ljepota"    -> catBeauty
        else         -> catOther
    }
}

val CroatianStrings = AppStrings(
    languageCode               = "hr",
    cancel                     = "Odustani",
    delete                     = "Obriši",
    close                      = "Zatvori",
    select                     = "Odaberi",
    or_                        = "ili",
    navHome                    = "Početna",
    navStats                   = "Statistike",
    navAdd                     = "Dodaj",
    navBudget                  = "Budgeti",
    greeting                   = "Dobar dan,",
    spendingThisMonth          = "Potrošnja ovaj mjesec",
    activeTracking             = "Aktivno praćenje",
    topCategories              = "Top kategorije",
    recentTransactions         = "Zadnje transakcije",
    searchResults              = "Rezultati pretrage",
    itemsSuffix                = "stavki",
    searchHint                 = "Pretraži po opisu ili kategoriji...",
    noTransactions             = "Nema transakcija",
    noTransactionsHint         = "Dodaj svoju prvu transakciju\nklikom na gumb + ispod",
    offlineBanner              = "Nema internetske veze — prikazuju se lokalni podaci",
    shakeTipShake              = "Protresite → skeniranje",
    shakeTipDouble             = "Dvaput → glasovni unos 🎤",
    deleteTransactionTitle     = "Obriši transakciju",
    deleteTransactionMessage   = "Jesi li siguran da želiš obrisati ovu transakciju?",
    statsTitle                 = "Statistike",
    statsSubtitle              = "Pregled tvoje potrošnje",
    filterByDay                = "Filtriraj po danu",
    expenseDistribution        = "Raspodjela troškova",
    spendingByCategory         = "Potrošnja po kategorijama",
    last7Days                  = "Zadnjih 7 dana",
    totalLabel                 = "Ukupno",
    dailyLabel                 = "Dnevno",
    lastMonthLabel             = "Prošli mj.",
    noDataForPeriod            = "Nema podataka za ovaj period",
    csvExportSuccess           = "CSV uspješno preuzet u Downloads",
    csvExportError             = "Greška pri izvozu — pokušaj ponovo",
    periodThisWeek             = "Ovaj tjedan",
    periodThisMonth            = "Ovaj mjesec",
    periodLastMonth            = "Prošli mjesec",
    periodThisQuarter          = "Ovaj kvartal",
    periodThisYear             = "Ova godina",
    allCategories              = "Sve kategorije",
    filterCategoriesTitle      = "Filtriraj kategorije",
    categoriesAvailableSuffix  = "kategorija dostupno",
    showingPrefix              = "Prikazano: ",
    removeFilter               = "Ukloni filter",
    catFood                    = "Hrana",
    catShopping                = "Trgovina",
    catTransport               = "Prijevoz",
    catEntertainment           = "Zabava",
    catHousing                 = "Kuća",
    catHealth                  = "Zdravlje",
    catClothing                = "Odijevanje",
    catBeauty                  = "Ljepota",
    catOther                   = "Ostalo",
    loginSubtitle              = "Prati svoju potrošnju pametno",
    loginWelcome               = "Dobrodošli nazad",
    loginWelcomeSub            = "Prijavite se na svoj račun",
    passwordLabel              = "Lozinka",
    rememberMe                 = "Zapamti me",
    loginButton                = "Prijava",
    noAccount                  = "Nemaš račun? Registriraj se",
    registerHeadline           = "Kreiraj račun",
    registerSubtitle           = "Počni pratiti svoju potrošnju",
    registerCardTitle          = "Novi račun",
    registerCardSubtitle       = "Ispunite sve podatke za registraciju",
    usernameLabel              = "Korisničko ime",
    confirmPasswordLabel       = "Potvrdi lozinku",
    registerButton             = "Registracija",
    hasAccount                 = "Već imaš račun? Prijavi se",
    addNewTransaction          = "Nova transakcija",
    editTransaction            = "Uredi transakciju",
    amountLabel                = "Iznos",
    scanButton                 = "Skeniraj",
    voiceButton                = "Glasovni",
    voiceListening             = "Slušam...",
    voiceLangLabel             = "Jezik:",
    voiceHelpTitle             = "Glasovni unos",
    voiceHelpDesc              = "Izgovori iznos i kategoriju. Aplikacija automatski prepoznaje oboje.",
    voiceExamplesCroatian      = "Primjeri — Hrvatski",
    voiceExamplesEnglish       = "Primjeri — English",
    voiceDecimalTip            = "Za decimale izgovori broj s točkom: \"25.50 hrana\"",
    voiceHelpOk                = "Razumijem",
    voiceRecognizedLabel       = "Prepoznato iz glasa",
    voiceNotRecognizedPrefix   = "Nije prepoznat iznos iz:",
    voiceNoSpeech              = "Govor nije prepoznat, pokušaj ponovo",
    voiceNoPerm                = "Dozvola za mikrofon nije odobrena",
    categoryLabel              = "Kategorija",
    addNewCategoryLabel        = "Nova",
    noteLabel                  = "Napomena",
    notePlaceholder            = "npr. Konzum, benzinska...",
    amountFromScan             = "Iznos prepoznat s računa",
    saveChanges                = "Spremi promjene",
    addTransactionButton       = "Dodaj transakciju",
    deleteCategoryTitle        = "Obriši kategoriju",
    deleteCategoryMessage      = "Sigurno želiš obrisati kategoriju \"%s\"?",
    budgetSubtitle             = "Postavi limite po kategoriji",
    budgetSummaryTitle         = "Ukupni budget ovaj mjesec",
    budgetCategorySection      = "Budgeti po kategoriji",
    budgetOverLimitSingular    = "kategorija prešla limit",
    budgetOverLimitPlural      = "kategorije prešle limit",
    budgetSetLimitHint         = "💡 Dodiri kategoriju za postavljanje limita",
    budgetWithinBudget         = "✅ Unutar budgeta",
    budgetNoLimitFormat        = "€%.2f  —  nema limita",
    budgetExceededByFormat     = "Prekoračen za €%.2f",
    budgetTapToSet             = "Dodiri za postavljanje limita",
    budgetDialogSetLimit       = "Postavi mjesečni limit za ovu kategoriju:",
    budgetSave                 = "Spremi",
    budgetRemoveLimit          = "Ukloni limit",
    loadMore                   = "Prikaži još",
)

val EnglishStrings = AppStrings(
    languageCode               = "en",
    cancel                     = "Cancel",
    delete                     = "Delete",
    close                      = "Close",
    select                     = "Select",
    or_                        = "or",
    navHome                    = "Home",
    navStats                   = "Statistics",
    navAdd                     = "Add",
    navBudget                  = "Budget",
    greeting                   = "Good day,",
    spendingThisMonth          = "This month's spending",
    activeTracking             = "Active tracking",
    topCategories              = "Top categories",
    recentTransactions         = "Recent transactions",
    searchResults              = "Search results",
    itemsSuffix                = "items",
    searchHint                 = "Search by description or category...",
    noTransactions             = "No transactions",
    noTransactionsHint         = "Add your first transaction\nby tapping the + button below",
    offlineBanner              = "No internet connection — showing local data",
    shakeTipShake              = "Shake → scan",
    shakeTipDouble             = "Double shake → voice input 🎤",
    deleteTransactionTitle     = "Delete transaction",
    deleteTransactionMessage   = "Are you sure you want to delete this transaction?",
    statsTitle                 = "Statistics",
    statsSubtitle              = "Your spending overview",
    filterByDay                = "Filter by day",
    expenseDistribution        = "Expense distribution",
    spendingByCategory         = "Spending by category",
    last7Days                  = "Last 7 days",
    totalLabel                 = "Total",
    dailyLabel                 = "Daily avg.",
    lastMonthLabel             = "Last mo.",
    noDataForPeriod            = "No data for this period",
    csvExportSuccess           = "CSV successfully saved to Downloads",
    csvExportError             = "Export error — please try again",
    periodThisWeek             = "This week",
    periodThisMonth            = "This month",
    periodLastMonth            = "Last month",
    periodThisQuarter          = "This quarter",
    periodThisYear             = "This year",
    allCategories              = "All categories",
    filterCategoriesTitle      = "Filter categories",
    categoriesAvailableSuffix  = "categories available",
    showingPrefix              = "Showing: ",
    removeFilter               = "Remove filter",
    catFood                    = "Food",
    catShopping                = "Shopping",
    catTransport               = "Transport",
    catEntertainment           = "Entertainment",
    catHousing                 = "Housing",
    catHealth                  = "Health",
    catClothing                = "Clothing",
    catBeauty                  = "Beauty",
    catOther                   = "Other",
    loginSubtitle              = "Track your expenses smartly",
    loginWelcome               = "Welcome back",
    loginWelcomeSub            = "Sign in to your account",
    passwordLabel              = "Password",
    rememberMe                 = "Remember me",
    loginButton                = "Log in",
    noAccount                  = "Don't have an account? Sign up",
    registerHeadline           = "Create account",
    registerSubtitle           = "Start tracking your expenses",
    registerCardTitle          = "New account",
    registerCardSubtitle       = "Fill in all details to register",
    usernameLabel              = "Username",
    confirmPasswordLabel       = "Confirm password",
    registerButton             = "Sign up",
    hasAccount                 = "Already have an account? Log in",
    addNewTransaction          = "New transaction",
    editTransaction            = "Edit transaction",
    amountLabel                = "Amount",
    scanButton                 = "Scan",
    voiceButton                = "Voice",
    voiceListening             = "Listening...",
    voiceLangLabel             = "Language:",
    voiceHelpTitle             = "Voice input",
    voiceHelpDesc              = "Say the amount and category. The app recognizes both automatically.",
    voiceExamplesCroatian      = "Examples — Croatian",
    voiceExamplesEnglish       = "Examples — English",
    voiceDecimalTip            = "For decimals, say the number with a dot: \"25.50 food\"",
    voiceHelpOk                = "Got it",
    voiceRecognizedLabel       = "Recognized from voice",
    voiceNotRecognizedPrefix   = "Amount not recognized from:",
    voiceNoSpeech              = "Speech not recognized, try again",
    voiceNoPerm                = "Microphone permission not granted",
    categoryLabel              = "Category",
    addNewCategoryLabel        = "New",
    noteLabel                  = "Note",
    notePlaceholder            = "e.g. Konzum, gas station...",
    amountFromScan             = "Amount recognized from receipt",
    saveChanges                = "Save changes",
    addTransactionButton       = "Add transaction",
    deleteCategoryTitle        = "Delete category",
    deleteCategoryMessage      = "Are you sure you want to delete category \"%s\"?",
    budgetSubtitle             = "Set limits per category",
    budgetSummaryTitle         = "Total budget this month",
    budgetCategorySection      = "Budgets by category",
    budgetOverLimitSingular    = "category exceeded limit",
    budgetOverLimitPlural      = "categories exceeded limit",
    budgetSetLimitHint         = "💡 Tap a category to set a limit",
    budgetWithinBudget         = "✅ Within budget",
    budgetNoLimitFormat        = "€%.2f  —  no limit",
    budgetExceededByFormat     = "Exceeded by €%.2f",
    budgetTapToSet             = "Tap to set a limit",
    budgetDialogSetLimit       = "Set monthly limit for this category:",
    budgetSave                 = "Save",
    budgetRemoveLimit          = "Remove limit",
    loadMore                   = "Load more",
)

data class AppLanguageState(
    val isEnglish: Boolean,
    val toggle: () -> Unit
)

val LocalStrings  = staticCompositionLocalOf<AppStrings> { CroatianStrings }
val LocalLanguage = staticCompositionLocalOf { AppLanguageState(false) {} }
